### ISSUE TITLE
"See the code on GitHub" link is not working

### ISSUE THREAD

**Issue by neynah** [ocdtrekkie/meteor-blocks#3]
In the left panel below the colours.

**Comment by ocdtrekkie** [comment]
I am going to investigate mostly for curiosity's sake, but given I don't think a lot of apps have a Github link inside them, and linking to outside places from Sandstorm isn't ideal, and the repo is linked in the app market... 

Will I make you sad if my solution is to remove the link?

**Comment by neynah** [comment]
I agree with you and promise I will not be sad. As you mentioned, the App Market already serves the same purpose. :)

**Comment by ocdtrekkie** [comment]
Apparently the solution is almost certainly https://docs.sandstorm.io/en/latest/developing/troubleshooting/#clicking-a-link-in-the-app-does-not-open-the-link

Which is a simple fix, and next time I release an update, I'll fix it.

**Comment by ocdtrekkie** [comment]
Fixed by d7dc4c24ad305d99fa10f3e8e34aa656d8d4e795
