### ISSUE TITLE
Feature request: export to VRML/X3D

### ISSUE THREAD

**Issue by zeigerpuppy** [ocdtrekkie/meteor-blocks#4]
It would be great to be able to export scenes as VRML/X3D so that they could be embedded in web pages or converted to other formats.

**Comment by ocdtrekkie** [comment]
A request like that would most likely be better for @stubailo 's repository. This is a fairly straightforward package of the upstream for Sandstorm.io.

**Comment by zeigerpuppy** [comment]
fair enough, I'll post it there, thanks

**Comment by ocdtrekkie** [comment]
Closing in favor of https://github.com/stubailo/meteor-blocks/issues/2
