### ISSUE TITLE
Link to 3D.meteor.com is dead

### ISSUE THREAD

**Issue by tart2000** [ocdtrekkie/meteor-blocks#6]
I believe Meteor closed their .meteor.com a couple of months ago. 
But is the project hosted anywhere else? 
I've started something similar, but based on three.js, where users can download an STL file for 3D printing: https://github.com/TechnoCultureClub/voxel-builder-V2 
It can be viewed here: http://cubecraft.technoculture.club

**Comment by ocdtrekkie** [comment]
@tart2000 Hey, that's neat!

Meteor Blocks is actually a project by @stubailo, this is just a Sandstorm port in this repo. I do not know if 3d.meteor.com has been moved elsewhere or not. However, you can try Meteor Blocks on Sandstorm by starting a demo from the Sandstorm App Market: https://apps.sandstorm.io/app/7kszn2vf4a4rhg5vcfmky6pcvc8tdwegwxv0fnjr286g778av3h0

**Comment by tart2000** [comment]
Thanks @ocdtrekkie! 
But I couldn't get the demo to work...

**Comment by ocdtrekkie** [comment]
Really? What issue are you having getting it to work? Can you explain where you got stuck or provide a screenshot?

**Comment by tart2000** [comment]
Well now it works... Weird. 
I think the first time I tried, the modal didn't show up...

**Comment by ocdtrekkie** [comment]
I actually recall the Sandstorm team has been working out some bugs with the demo modal recently. I will tag @kentonv here in case this is useful feedback for him.

**Comment by ocdtrekkie** [comment]
As a sidebar, @tart2000, you should totally consider packaging your app for Sandstorm! It is relatively easy to tie accounts and permissions to apps built on... pretty much any platform that runs on a Linux server and presents a web interface. The biggest perk is that people can host Sandstorm servers (and hence your app) either in the cloud or on-premises, and you as the developer don't have to worry about storage or bandwidth or anything like that.
